### ISSUE TITLE
Compatibility with Webpack + css modules

### ISSUE THREAD

**Issue by dave-cooper-cko** [ismamz/postcss-click#1]
Hey there - I was just wondering if there is a way to get this plugin to work with postcss + css modules + webpack. The current line in my Webpack config looks like this:

`{ test: /\.css$/, include: path.resolve(__dirname, 'src/'), loader: ExtractTextPlugin.extract('css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss?parser=postcss-less') },`

I'm not sure how to tell postcss to use postcss-click in my Webpack config.

Any ideas?

**Comment by ai** [comment]
Use postcss-modules (same CSS Modules but with other PostCSS plugins) before postcss-click

**Comment by dave-cooper-cko** [comment]
If I were using postcss modules, how would I then tell it to use postcss-click?

**Comment by dave-cooper-cko** [comment]
Oh right! I've just worked out what you meant.

Thanks!
